### PR TITLE
change CDN links to jsDelivr

### PR DESCRIPTION
**Pull request by MartinKolarik**
[jsDelivr](https://github.com/jsdelivr/jsdelivr) recently added a npm proxy and now it's basically unpkg with extra features and much better stability

### CODE REVIEW

**Comment by evs-chris** [comment]
Oooh! Is there any possibility of package usage metrics?

**Comment by MartinKolarik** [comment]
Not yet but detailed stats for each package will be available soon.

**Comment by evs-chris** [comment]
Am I understanding correctly that we could recommend this for easy automatic bundling of plugins using combine?

**Comment by MartinKolarik** [comment]
Yep. We could also provide direct links for some combinations. For example former legacy build would be just ractive + polyfills.

**Pull request merged**
