### PR TITLE
Aded css tweaks an inline demo

### PR DESCRIPTION
**Pull request by sabob**
Made the heading font-weight less, changed sidebar colors. Added an intro inline demo.

### CODE REVIEW

**Comment by sabob** [comment]
Use PR if deemed proper, otherwise reject ;-)

**Comment by fskreuz** [comment]
Was planning to add instructions for Windows last night, but was busy with other things.

We might want platform-specific instructions. IIRC, python and pip for Windows comes in an installer. For ubuntu, it's simply a `sudo apt-get install python python-pip`. virtualenv can then be installed via pip. Then platform-specific activate and deactivate.

**Comment by evs-chris** [comment]
I pulled all of the changes except the inline demo over while I was fiddling with the index page. I'll add examples as playground entries and maybe get an inline embeddable version of the playground. Thanks!

**Comment by sabob** [comment]
Embeddable playground sounds great. What I like about inline demos, is you get instant feedback without breaking context eg. switching to a different view such as playground or jsfiddle

**Comment by sabob** [comment]
There is a bug in the sidebar, it doesn't set the selected item to active. I think this is a bug in mkdocs though.

**Comment by evs-chris** [comment]
I noticed that the other day. I'm not sure what changed, but it _did_ work when we first started using mkdocs. I don't see any exceptions, unhandled or otherwise, that seem relevant on page load. I also don't have any experience with the bootstrap thingy that does the scroll spying.

**Comment by fskreuz** [comment]
I'm working on the layout mentioned in https://github.com/ractivejs/ractivejs.github.io/issues/16. I think the scrollspy handled the boldening of the sidebar items. I'm considering using CSS [`:target`](https://developer.mozilla.org/en-US/docs/Web/CSS/:target) for that instead.

**Comment by sabob** [comment]
Seems the the base.html in custom_theme folder doesn't have the spyscroll enabled. Not sure how that works either.

**Comment by evs-chris** [comment]
Ah! That actually makes sense. The scroll container is now a div rather than the body, so it's not getting scroll events on the element it is expecting any more. I'll see if there's a way to hook it up on the div.

**Pull request closed without merging**
