### PR TITLE
The white theme

### PR DESCRIPTION
**Pull request by fskreuz**
The plain and blindingly white theme.

I may need help in putting back the interactive bits since I moved markup around alot and 😱 broke them.

capture

### CODE REVIEW

**Comment by evs-chris** [comment]
I like the menus! The main menu on mobile probably needs to be slightly more discoverable, as I was scratching my head for a minute.

I did have to darken the body color a bit to be able to read it comfortably on my monitor. It'll take a bit of playing to get the playground re-integrated. There are some fixed positioning machinations that have to take place to get everything working correctly. I'm thinking about going ahead and pushing 0.9 on Friday, so this may be an after-launch priority?

**Comment by fskreuz** [comment]
0.9 on Friday sounds good to me.

The toc menu was supposed to go away in mobile, and the hamburger was supposed to toggle the main menu. Just added both to try it out. 😄

**Comment by andreujuanc** [comment]
Minimalism is trendy nowadays x)
+1

**Comment by kouts** [comment]
@fskreuz theme looks good!

**Comment by fskreuz** [comment]
I think I'll just go ahead and merge this and adjust everything along the way together with the content.

**Pull request merged**
