### PR TITLE
Update event reference with context

### PR DESCRIPTION
**Pull request by kouts**
Change the first argument from event to ctx, as first argument of event handlers is a context object (ctx)

### CODE REVIEW

**Comment by fskreuz** [comment]
Wondering if a full `context` would convey the idea better. Not a fan of abbreviations, but that's just me. :D

**Comment by fskreuz** [comment]
🎉

**Comment by kouts** [comment]
@fskreuz thanks, can you also check if this is correct: https://ractive.js.org/concepts/#event-context

> The context object is a special instance of a context object augmented with additional event-related properties where applicable.

Should this also change to context? https://ractive.js.org/concepts/#stopping-propagation

**Comment by fskreuz** [comment]
As far as I know, yes. All events, DOM or component, now supply an instance of `Context` when using `ractive.on` to listen for them. As a quick sanity check, I'll pull @evs-chris into the conversation. 😄

**Comment by fskreuz** [comment]
Ahh... no. That's confusing. 😄

**Comment by kouts** [comment]
@fskreuz could you also please check the example at https://ractive.js.org/concepts/#stopping-propagation
I think this also needs changing from event to context am I correct?

**Pull request merged**
